name: Upload Electron Binaries to Github

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos-x86', image: 'macos-latest' },
            # { name: 'macos-arm64', image: 'macos-latest-xlarge' },
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Add WiX Toolset to PATH
        if: matrix.os.name == 'windows'
        shell: pwsh
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Sign the app
        if: matrix.os.name == 'macos-arm64' || matrix.os.name == 'macos-x86'
        env:
          APPLE_DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION_CERT }}
          APPLE_DEVELOPER_ID_INSTALLER_CERT: ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER_CERT }}
          APPLE_KEYCHAIN: aiconsole.keychain
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          echo $APPLE_DEVELOPER_ID_APPLICATION_CERT | base64 --decode > electron/DeveloperIdApplication.p12
          echo $APPLE_DEVELOPER_ID_INSTALLER_CERT | base64 --decode > electron/DeveloperIdInstaller.p12
          security create-keychain -p "" $APPLE_KEYCHAIN
          security default-keychain -s $APPLE_KEYCHAIN
          security unlock-keychain -p "" $APPLE_KEYCHAIN
          security import electron/DeveloperIdApplication.p12 -k $APPLE_KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security import electron/DeveloperIdInstaller.p12 -k $APPLE_KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s $APPLE_KEYCHAIN
          security list-keychains -s $APPLE_KEYCHAIN

      - name: Publish app
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: cd electron && yarn run publish
